// AUTH
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOG_OUT_SUCCESS = "SET_LOG_OUT_SUCCESS";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//SEARCH
export const SEARCH_RECIPES_SUCCESS = "SEARCH_RECIPES_SUCCESS";
export const SEARCH_RECIPES_LOADING = "SEARCH_RECIPES_LOADING";
